### ISSUE TITLE
Tag convention: With or without `v` prefix?

### ISSUE THREAD

**Issue by mokagio** [Automattic/bash-cache-buildkite-plugin#14]
While working on [adding the scheduled cache rebuilding pipeline on Pocket Casts iOS](https://github.com/shiftyjelly/pocketcasts-ios/pull/3667), I noticed the latest version is tagged [`1.7.0`](https://github.com/Automattic/bash-cache-buildkite-plugin/releases/tag/1.7.0). This name, while correct SemVer-wise, breaks the pattern from the previous versions, which were tagged using the `v` prefix: `v1.6.1`, `v1.6.0`, etc.

<img width="615" alt="Screen Shot 2021-12-07 at 4 07 36 pm" src="https://user-images.githubusercontent.com/1218433/145054356-7fb5d76f-cbdd-47d8-8a03-f96fcb8b47bf.png">

@AliSoftware, you created that tag, so I'm wondering if this was intentional or muscle-memory from other repos 😄  cc @jkmassel 

I did a quick search for "1.7.0" in Slack but it came out short.

**Comment by AliSoftware** [comment]
I did a minor bump because the changes introduced in the new version (via #8) consisted on adding a new feature (here a new `bin/` command), as opposed to fixing a bug. And a new feature warrants a minor version according to SemVer, so that was my reasoning back then for going up to `1.7.0` there 🙂 

(I am not sure if previous tags and the version numbers we chose before did ensure we followed SemVer up until now. But because my brain is wired to default to SemVer anyway, I didn't really think about it tbh 😃  and even in case we didn't yet follow SemVer before 1.7.0 then… that was a good time as any to start doing it 😛 )

**Comment by mokagio** [comment]
@AliSoftware thanks for the context. 😄 

I wasn't clear, though, my question is more about why it's `1.7.0` instead of `v1.7.0`, i.e. why is there no `v` prefix in that tag? 

Is it a new standard for this repo, or something that slipped? 

I don't mind either way just wanted to be sure 😄

**Comment by AliSoftware** [comment]
Oh!
I just never realized the previous versions had a `v` there 😮 (proof: I missed it again during this very conversation 😂 )

I have no idea why we had it in the previous tags, if it was intentional, or just came to be for no specific reason (my guess for the latter).
Or maybe because that was how some example in the Buildkite doc was written so Jeremy used a similar naming convention as the Buildkite doc back then? (though I took a quick look at the docs for Buildkite plugins and couldn't find an explicit strong suggestion to use `v`-prefixed tags… except maybe [this "for example, v1.2.3" instance](https://buildkite.com/docs/plugins/using#:~:text=(for%20example%2C%20v1.2.3)))

To my knowledge the only main (ie commonly-updated) repo where we have the `v` prefix is Gutenberg-Mobile, and probably for historical reasons too or something, while all other repos don't have that `v` prefix. So unless it was a recommendation or need set by Buildkite (which doesn't seem to be), I vote for dropping the `v` from now on?

**Comment by jkmassel** [comment]
Yeah we really don't _need_ it, I just copied the Buildkite format 🤷

**Comment by mokagio** [comment]
Sounds good to me 👍
